import { MACHINES } from './machine.mjs';
const $=id=>document.getElementById(id),fmt=n=>n.toLocaleString('ja-JP');
const worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});
let selected=0,running=false,pending=0,credit=0,lastTime=performance.now();
const cache=[];const ink='#8a3a2e',pink='#ff678e',paper='#fffaf2',line='#dec9ba';
function send(type,count=0,index=selected){pending++;worker.postMessage({type,index,count});}
function fail(){running=false;pending=Math.max(0,pending-1);$('error').hidden=false;$('error').textContent='この子を読み込めませんでした。ページを再読み込みしてください。';}
worker.onerror=fail;
worker.onmessage=({data})=>{pending=Math.max(0,pending-1);if(data.error){fail();return;}cache[data.index]=data.snapshot;const child=document.querySelector(`[data-machine="${data.index}"]`);child.classList.toggle('sleeping',data.snapshot.halted);$('child-'+data.index).textContent=data.snapshot.halted?'すやすや。':data.snapshot.steps?fmt(data.snapshot.steps)+' ほ':'まだ、まっしろ';if(data.index===selected){if(data.snapshot.halted)running=false;render(data.snapshot);}};
function pause(){running=false;credit=0;if(cache[selected])render(cache[selected]);}
function choose(i){pause();selected=i;document.querySelectorAll('.child').forEach((el,j)=>{el.classList.toggle('selected',i===j);el.setAttribute('aria-pressed',String(i===j));});if(cache[i])render(cache[i]);else{['play','step','reset'].forEach(id=>$(id).disabled=true);send('snapshot',0,i);}}
document.querySelectorAll('.child').forEach(el=>el.onclick=()=>choose(Number(el.dataset.machine)));
$('play').onclick=()=>{running=!running;credit=0;render(cache[selected]);};
$('step').onclick=()=>{pause();send('advance',1);};
$('reset').onclick=()=>{pause();send('reset');};
$('next').onclick=()=>choose((selected+1)%5);
$('journey').onclick=()=>{$('speed').value='2400000';running=true;credit=0;render(cache[selected]);};
$('speed').onchange=()=>{credit=0;render(cache[selected]);};
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
function frame(now){const dt=Math.min(.05,(now-lastTime)/1000);lastTime=now;if(running&&!document.hidden&&pending===0&&cache[selected]&&!cache[selected].halted){credit+=dt*Number($('speed').value);let count=Math.min(40000,Math.floor(credit));if(selected===4)count=Math.min(count,24);if(count){credit-=count;credit=Math.min(credit,40000);send('advance',count);}}requestAnimationFrame(frame);}requestAnimationFrame(frame);
function clear(id){const c=$(id),g=c.getContext('2d');g.fillStyle=paper;g.fillRect(0,0,c.width,c.height);return g;}
function text(g,s,x,y,size=18,color=ink){g.fillStyle=color;g.font=`${size}px "DotGothic16", monospace`;g.fillText(s,x,y);}
function face(g,x,y,s,sleep){g.fillStyle=ink;g.fillRect(x+s,y,s*8,s*8);g.fillRect(x,y+s*2,s*10,s*5);g.fillStyle=paper;g.fillRect(x+s*2,y+s*3,s*2,s*(sleep?.35:1.5));g.fillRect(x+s*6,y+s*3,s*2,s*(sleep?.35:1.5));g.fillStyle=pink;g.fillRect(x+s,y+s*5,s*2,s);g.fillRect(x+s*7,y+s*5,s*2,s);}
function draw(s){const c=world;const w=c.clientWidth<500?480:840;if(c.width!==w)c.width=w;const cx=w/2;const g=clear('world');text(g,s.halted?'おやすみ。':s.steps===0?'まだ、何も書いていない。':running?'右へ、左へ。':'ここで、ひと休み。',30,42,18);const cell=32,start=cx-24*cell;for(let i=0;i<49;i++){let x=start+i*cell;g.fillStyle=s.view[i]?ink:paper;g.fillRect(x,228,cell-2,32);g.strokeStyle=line;g.strokeRect(x,228,cell-2,32);}g.strokeStyle=pink;g.lineWidth=3;g.strokeRect(cx-1,226,32,36);g.lineWidth=1;face(g,cx-34,116,10,s.halted);text(g,s.halted?'z z z':s.state,cx+62,110,24,pink);text(g,'↓',cx+3,218,18,pink);text(g,'いまいるマス '+fmt(s.pos),30,305,14);text(g,'白 = 0    黒 = 1',w-200,305,14);$('world').setAttribute('aria-label',`${s.name}、${fmt(s.steps)}歩。状態${s.state}。${s.halted?'停止しました。':''}`);
 const rows=s.rows,lo=s.low,span=Math.max(1,s.high-lo+1),tg=clear('trace'),ag=clear('amount');tg.strokeStyle=line;tg.beginPath();tg.moveTo(360,20);tg.lineTo(360,280);tg.stroke();if(rows.length){const end=s.steps,first=Math.max(0,rows[0].step-(selected===3?157257:1));for(const r of rows){const y=25+(r.step-first)/Math.max(1,end-first)*245;tg.fillStyle=pink;tg.fillRect(30+(r.lo-lo)/span*660,y,Math.max(2,(r.hi-r.lo+1)/span*660),Math.max(1,245/rows.length));}ag.strokeStyle=pink;ag.lineWidth=2;ag.beginPath();if(first===0)ag.moveTo(35,265);rows.forEach((r,i)=>{const x=35+(r.step-first)/Math.max(1,end-first)*650,y=265-r.ones/Math.max(1,s.peak)*215;if(i===0&&first!==0)ag.moveTo(x,y);else ag.lineTo(x,y);});ag.stroke();text(ag,fmt(s.peak)+' こ',35,30,16);text(ag,fmt(s.ones)+' こ',550,30,16,pink);}else{text(tg,'ここから、はじまる。',230,155,20);text(ag,'まだ、０。',290,155,20);}text(tg,fmt(lo),20,295,12);text(tg,fmt(s.high),610,295,12);const tape=clear('tape');s.overview.forEach((density,i)=>{tape.globalAlpha=density;tape.fillStyle=ink;tape.fillRect(i*840/360,0,Math.ceil(840/360),44);});tape.globalAlpha=1;
}
function render(s){if(!s)return;$('who').textContent=s.name;$('steps').textContent=fmt(s.steps);$('ones').textContent=fmt(s.ones);const status=s.halted?'すやすや。':running?'歩いています。':s.steps?'ここで、ひと休み。':'まだ、まっしろ。';if($('status').textContent!==status)$('status').textContent=status;$('play').disabled=s.halted;$('step').disabled=s.halted;$('reset').disabled=false;$('save').disabled=!s.steps;$('play').textContent=running?'ひと休み ‖':'あるかせる →';$('encore').hidden=!s.halted;$('long-note').hidden=selected!==3||s.halted;$('ending').textContent=`${fmt(s.steps)}歩で、眠りました。${fmt(s.ones)}個の１が、残っています。`;$('speed-note').textContent=$('speed').value==='4'?'一歩ずつ、見える速さ。':$('speed').value==='1200'?'少しずつ、跡が育つ。':'途中の計算も省かずに。速さは端末によって変わります。';const r=s.last;$('instruction-lead').textContent=r?'最後に実行した規則。':'まだ何も、書いていない。';$('state').textContent=r?r.state:'A';$('read').textContent=r?r.read:'—';$('write').textContent=r?r.write:'—';$('direction').textContent=r?r.move>0?'右 →':'← 左':'—';$('next-state').textContent=r?r.next:'—';$('rule-caption').textContent=s.name+'の遷移表';$('rule-body').innerHTML=Object.entries(MACHINES[selected].rules).flatMap(([state,rs])=>rs.map(([w,d,n],bit)=>`<tr class="${r&&r.state===state&&r.read===bit?'current':''}"><td>${state}</td><td>${bit}</td><td>${w}</td><td>${d>0?'→':'←'}</td><td>${n}</td></tr>`)).join('');$('span').textContent=fmt(s.high-s.low+1)+' マス';$('record-copy').textContent=s.halted?'動きは止まっても、歩いた跡はここに。':'一歩進むたびに、ここへ残ります。';$('record-summary').textContent=s.steps?`いちばん多かった１：${fmt(s.peak)}個（${fmt(s.peakAt)}歩目）。いま：${fmt(s.ones)}個。`:'まっしろも、ひとつの状態。';$('record-scale').textContent=(selected===3?'通った範囲は157,257歩ごとにまとめ、１の数はその時点を記録。最後の停止時点も記録します。':'１歩ごとに記録。')+(s.rows.length===720?'表示は直近720件。':'')+' テープ全景の濃さは、その範囲にある１の割合です。';draw(s);}
$('save').onclick=()=>{const s=cache[selected],c=document.createElement('canvas');c.width=1500;c.height=1080;const g=c.getContext('2d');g.fillStyle=paper;g.fillRect(0,0,c.width,c.height);text(g,'とまる。 / '+s.name,70,85,38);text(g,fmt(s.steps)+' ほ  /  残った１ '+fmt(s.ones)+' こ',70,140,24);g.drawImage($('world'),70,180,document.getElementById("world").width,330);text(g,'通ったところ',70,580,24);text(g,'残った１',790,580,24);g.drawImage($('trace'),70,610,660,275);g.drawImage($('amount'),790,610,660,275);text(g,'ひゅーまん  /  hyu-man.com/halt/',70,1010,20);text(g,selected===3?'157,257歩ごとの記録＋停止時点':'１歩ごとの記録（最大720件）',70,950,18);c.toBlob(blob=>{if(!blob)return;if(cardURL)URL.revokeObjectURL(cardURL);cardURL=URL.createObjectURL(blob);$('card-image').src=cardURL;$('card-download').href=cardURL;$('card-download').download=`halt_${s.id}_${s.steps}.png`;$('postcard').showModal();});};
send('snapshot');document.fonts.ready.then(()=>{if(cache[selected])draw(cache[selected]);});



new ResizeObserver(()=>{if(cache[selected])draw(cache[selected]);}).observe(document.getElementById("world"));



let cardURL=null; $('close-card').onclick=()=>$('postcard').close();
